global using BuildingBlocks.Domain;
global using BuildingBlocks.Domain.Aggregates;
global using BuildingBlocks.Domain.Entities;
global using BuildingBlocks.Domain.Events;
global using BuildingBlocks.Domain.Results;
global using BuildingBlocks.Domain.ValueObjects;
global using System;
global using System.Collections.Generic;
global using System.Linq;
