apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distributed-commerce-dev

bases:
  - ../../base
  - ../../infrastructure
  - ../../services

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: api-gateway
    count: 1
  - name: identity-service
    count: 1
  - name: catalog-service
    count: 1
  - name: order-service
    count: 1
  - name: payment-service
    count: 1
  - name: inventory-service
    count: 1
  - name: shipping-service
    count: 1
  - name: notification-service
    count: 1
  - name: analytics-service
    count: 1

configMapGenerator:
  - name: shared-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Development

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
    target:
      kind: Deployment
      labelSelector: "tier=backend"
