# External Secrets Operator Configuration
# Manages secrets from external secret stores (AWS Secrets Manager, Azure Key Vault, HashiCorp Vault, etc.)

---
# Install External Secrets Operator
# kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
# kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/external-secrets.yaml

---
# SecretStore for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: distributed-commerce
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
# SecretStore for Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: distributed-commerce
spec:
  provider:
    azurekv:
      tenantId: "your-tenant-id"
      vaultUrl: "https://your-vault.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: client-id
        clientSecret:
          name: azure-secret-sp
          key: client-secret

---
# SecretStore for HashiCorp Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: distributed-commerce
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "distributed-commerce"
          serviceAccountRef:
            name: external-secrets-sa

---
# ExternalSecret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: distributed-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager  # or azure-keyvault, vault-backend
    kind: SecretStore
  target:
    name: shared-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: distributed-commerce/database
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: distributed-commerce/database
      property: password

---
# ExternalSecret for JWT Configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-config
  namespace: distributed-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: shared-secrets
    creationPolicy: Merge
  data:
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: distributed-commerce/jwt
      property: secret_key
  - secretKey: JWT_ISSUER
    remoteRef:
      key: distributed-commerce/jwt
      property: issuer
  - secretKey: JWT_AUDIENCE
    remoteRef:
      key: distributed-commerce/jwt
      property: audience

---
# ExternalSecret for Third-Party API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: distributed-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: shared-secrets
    creationPolicy: Merge
  data:
  - secretKey: STRIPE_SECRET_KEY
    remoteRef:
      key: distributed-commerce/stripe
      property: secret_key
  - secretKey: STRIPE_WEBHOOK_SECRET
    remoteRef:
      key: distributed-commerce/stripe
      property: webhook_secret
  - secretKey: SENDGRID_API_KEY
    remoteRef:
      key: distributed-commerce/sendgrid
      property: api_key
  - secretKey: TWILIO_ACCOUNT_SID
    remoteRef:
      key: distributed-commerce/twilio
      property: account_sid
  - secretKey: TWILIO_AUTH_TOKEN
    remoteRef:
      key: distributed-commerce/twilio
      property: auth_token
  - secretKey: FIREBASE_SERVER_KEY
    remoteRef:
      key: distributed-commerce/firebase
      property: server_key

---
# Service Account for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: distributed-commerce
  annotations:
    # For AWS IRSA
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-role
    # For Azure Workload Identity
    azure.workload.identity/client-id: "your-client-id"
