global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'distributed-commerce'
    environment: 'development'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'api-gateway'

  # Order Service
  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-api:8080']
        labels:
          service: 'order-service'

  # Inventory Service
  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory-api:8080']
        labels:
          service: 'inventory-service'

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-api:8080']
        labels:
          service: 'payment-service'

  # Catalog Service
  - job_name: 'catalog-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['catalog-api:8080']
        labels:
          service: 'catalog-service'

  # Shipping Service
  - job_name: 'shipping-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['shipping-api:8080']
        labels:
          service: 'shipping-service'

  # Analytics Service
  - job_name: 'analytics-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['analytics-api:8080']
        labels:
          service: 'analytics-service'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-api:8080']
        labels:
          service: 'notification-service'

  # Identity Service
  - job_name: 'identity-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['identity-api:8080']
        labels:
          service: 'identity-service'

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
        labels:
          service: 'kafka'

  # PostgreSQL Exporter (if you add postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Redis Exporter (if you add redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
