apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distributed-commerce-staging

bases:
  - ../../base
  - ../../infrastructure
  - ../../services

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: api-gateway
    count: 2
  - name: identity-service
    count: 2
  - name: catalog-service
    count: 2
  - name: order-service
    count: 2
  - name: payment-service
    count: 2
  - name: inventory-service
    count: 2
  - name: shipping-service
    count: 2
  - name: notification-service
    count: 2
  - name: analytics-service
    count: 2

configMapGenerator:
  - name: shared-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Staging
