apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: distributed-commerce
  labels:
    app: api-gateway
    tier: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: gateway
    spec:
      containers:
      - name: api-gateway
        image: distributed-commerce/api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: JWT_SECRET_KEY
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: JWT_ISSUER
        - name: Jwt__Audience
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: JWT_AUDIENCE
        - name: OpenTelemetry__JaegerEndpoint
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: JAEGER_ENDPOINT
        - name: Serilog__WriteTo__0__Args__serverUrl
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: SEQ_SERVER_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: distributed-commerce
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: distributed-commerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
