apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: distributed-commerce
  labels:
    app: order-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
    spec:
      containers:
      - name: order-service
        image: distributed-commerce/order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-service;Port=5432;Database=OrderDb;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: POSTGRES_PASSWORD
        - name: Kafka__BootstrapServers
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: Kafka__SchemaRegistryUrl
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: KAFKA_SCHEMA_REGISTRY_URL
        - name: OpenTelemetry__JaegerEndpoint
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: JAEGER_ENDPOINT
        - name: Serilog__WriteTo__0__Args__serverUrl
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: SEQ_SERVER_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: distributed-commerce
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: distributed-commerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
