apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: distributed-commerce
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry-service:8081"
  REDIS_CONNECTION: "redis-service:6379"
  JAEGER_ENDPOINT: "http://jaeger-service:4317"
  SEQ_SERVER_URL: "http://seq-service:5341"
  ELASTICSEARCH_URI: "http://elasticsearch-service:9200"
