apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distributed-commerce

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: distributed-commerce
  app.kubernetes.io/managed-by: kustomize
